
from keras.models import model_from_json
import coremltools
import globalData
globalData.init()

# load json and create model
json_file = open('src/model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
# load weights into new model
model.load_weights("src/model.h5")
print("Loaded model from disk")

coreMLModel = coremltools.converters.keras.convert(model, input_names = ['workoutSummary'],
                                                         output_names = ['workoutName'],
                                                         class_labels = globalData.CLASSIFICATIONS)
coreMLModel.author = 'Chappy Asel'
coreMLModel.license = 'MIT'
coreMLModel.short_description = 'Determines a workout name based on the workout summary'
coreMLModel.input_description['workoutSummary'] = 'The summary generated by the workout'
coreMLModel.output_description['workoutName'] = 'The suggested name of the workout'
coreMLModel.save('src/workoutNameModel.mlmodel')
